// SCIMCBrowser.h — RyukGram-Fork
// MobileConfig override browser + store. Reads the id-name mapping and current
// overrides from the per-user data dir under the live MobileConfig container
// (manager _containerPath / App Group / Documents/mobileconfig/<uid>.data/).
// The name table is never pre-seeded from the bundle: it must already exist in
// the container (generated by SCIIdNameMapGenerator or placed by the user).
// Browse every config/param BY NAME, 3-state override each param (SYS / OFF / ON),
// and write mc_overrides.json in the exact internal format.

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSInteger, SCIMCOverrideState) {
    SCIMCOverrideSYS = 0,   // no override (remove entry) — app/server value
    SCIMCOverrideOFF = 1,   // forced false
    SCIMCOverrideON  = 2,   // forced true
};

@interface SCIMCOverrideStore : NSObject
+ (instancetype)shared;

@property (nonatomic, readonly) NSURL *mobileconfigRoot;   // .../Documents/mobileconfig/
@property (nonatomic, readonly) NSURL *userDataDir;        // .../mobileconfig/<uid>.data/
@property (nonatomic, readonly) NSArray<NSNumber *> *configIDs;

- (void)reload;
- (NSString *)nameForConfig:(NSInteger)cid;
- (NSDictionary<NSNumber *, NSString *> *)paramsForConfig:(NSInteger)cid;
- (NSString *)nameForConfig:(NSInteger)cid param:(NSInteger)idx;
- (NSArray<NSNumber *> *)configIDsMatching:(nullable NSString *)query;   // token search

- (SCIMCOverrideState)stateForConfig:(NSInteger)cid param:(NSInteger)idx;
- (nullable NSString *)stringValueForConfig:(NSInteger)cid param:(NSInteger)idx; // raw ("true"/"false"/…) or nil
- (void)setState:(SCIMCOverrideState)state forConfig:(NSInteger)cid param:(NSInteger)idx;
- (BOOL)save:(NSError **)error;

- (BOOL)deployBundledMappingOverwrite:(NSError **)error;
- (void)applyInternalPreset;   // employee/dogfood/dev/internal one-tap
@end

@interface SCIMCBrowserListController : UIViewController
@end

NS_ASSUME_NONNULL_END
