#import "SCIDefaults.h"
#import "Utils.h"
#import "UI/Notification/SCINotificationCenter.h"
#import "UI/Notification/SCINotificationMirror.h"

NSDictionary *SCIDefaultsDictionary(void) {
	return @{
		@"hide_ads": @(YES),
		@"hide_ads_feed": @(YES),
		@"hide_ads_stories": @(YES),
		@"hide_ads_reels": @(YES),
		@"hide_ads_explore": @(YES),
		@"hide_ads_shopping": @(YES),
		@"copy_description": @(YES),
		@"profile_copy_button": @(YES),
		@"detailed_color_picker": @(YES),
		@"remove_screenshot_alert": @(YES),
		@"voice_call_confirm": @(NO),
		@"video_call_confirm": @(NO),
		@"keep_deleted_message": @(NO),
		@"deleted_messages_log_enabled": @(NO),
		@"deleted_messages_log_reactions": @(NO),
		@"deleted_messages_keepalive": @(NO),
		@"dm_log_date_format": @"relative",
		@"hide_suggested_stories": @(NO),
		@"hide_story_highlights": @(NO),
		@"hide_stories_midcards": @(NO),
		@"hide_testflight_nag": @(YES),
		@"profile_analyzer_track_visits": @(NO),
		@"profile_analyzer_record_snapshots": @(NO),
		@"profile_analyzer_snapshot_cap": @(20),
		@"story_tray_actions": @(NO),
		@"zoom_profile_photo": @(NO),
		@"sci_followlist_sort_enabled": @(NO),
		@"follow_indicator": @"off",
		@"profile_note_copy": @(NO),
		@"disable_disappearing_mode_swipe": @(NO),
		@"hide_voice_call_button": @(NO),
		@"hide_video_call_button": @(NO),
		@"sci_silence_calls": @(NO),
		@"fake_location_enabled": @(NO),
		@"show_fake_location_map_button": @(NO),
		@"fake_location_lat": @(48.8584),
		@"fake_location_lon": @(2.2945),
		@"fake_location_name": @"Eiffel Tower",
		@"fake_location_presets": @[],
		@"messages_only": @(NO),
		@"messages_only_hide_tabbar": @(NO),
		@"messages_only_hide_search": @(NO),
		@"hide_send_to_group": @(NO),
		@"confirm_send_to_group": @(NO),
		@"share_sheet_pin_threads": @(NO),
		@"share_sheet_pinned_thread_ids": @[],
		@"hide_reels_friends_bubbles": @(NO),
		@"hide_reels_floating_social_context": @(NO),
		@"hide_made_with_edits": @(NO),
		@"hide_reels_repost": @(NO),
		@"hide_notes_tray": @(NO),
		@"repost_confirm": @(NO),
		@"emoji_reaction_confirm": @(NO),
		@"story_like_confirm": @(NO),
		@"disable_safe_mode": @(NO),
		@"tweak_settings_app_launch": @(NO),
		@"gallery_folders": @[],
		@"full_followers_count": @(NO),
		@"full_posts_count": @(NO),
		@"reel_card_full_views": @(NO),
		@"reel_card_show_likes": @(NO),
		@"reel_card_show_date": @(NO),
		@"reel_card_fetch_missing": @(NO),
		@"reel_card_shortened_numbers": @(NO),
		@"fake_follower_count": @(NO),
		@"fake_follower_count_value": @"",
		@"fake_following_count": @(NO),
		@"fake_following_count_value": @"",
		@"fake_post_count": @(NO),
		@"fake_post_count_value": @"",
		@"fake_verified": @(NO),
		@"launch_tab": @"default",
		@"save_profile": @(YES),

		@"liquid_glass_buttons": @(NO),
		@"liquid_glass_surfaces": @(NO),
		@"liquid_glass_force_off": @(NO),
		@"liquid_glass_progressive_blur": @(NO),
		@"liquid_glass_tabbar_mode": @"default",

		@"flex_app_launch": @(NO),
		@"flex_app_start": @(NO),
		@"flex_instagram": @(NO),

		@"hide_stories_tray": @(NO),
		@"hide_meta_ai": @(NO),
		@"hide_entire_feed": @(NO),
		@"hide_explore_grid": @(NO),
		@"hide_explore_tab": @(NO),
		@"hide_feed_tab": @(NO),
		@"hide_reels_tab": @(NO),
		@"hide_messages_tab": @(NO),
		@"hide_create_tab": @(NO),
		@"hide_friends_map": @(NO),
		@"hide_metrics": @(NO),
		@"hide_reels_blend": @(NO),
		@"hide_reels_header": @(NO),
		@"hide_trending_searches": @(NO),
		@"no_suggested_users": @(NO),
		@"no_suggested_chats": @(NO),
		@"no_suggested_threads": @(NO),
		@"no_suggested_reels": @(NO),
		@"no_suggested_post": @(NO),
		@"no_suggested_account": @(NO),
		@"no_profile_suggested_users": @(NO),
		@"no_recent_searches": @(NO),
		@"no_seen_receipt": @(NO),
		@"remove_lastseen": @(NO),

		@"like_confirm": @(NO),
		@"like_confirm_reels": @(NO),
		@"note_like_confirm": @(NO),
		@"note_react_confirm": @(NO),
		@"follow_confirm": @(NO),
		@"follow_request_confirm": @(NO),
		@"post_comment_confirm": @(NO),
		@"refresh_reel_confirm": @(NO),
		@"shh_mode_confirm": @(NO),
		@"voice_message_confirm": @(NO),
		@"change_direct_theme_confirm": @(NO),

		@"disable_feed_autoplay": @(NO),
		@"disable_haptics": @(NO),
		@"disable_scrolling_reels": @(NO),
		@"disable_typing_status": @(NO),
		@"disable_view_once_limitations": @(NO),
		@"enable_hidden_texteffectsstyles": @(NO),
		@"reels_show_scrubber": @(NO),
		@"reels_playback_speed": @(NO),
		@"reels_playback_speed_rate": @(1.0),
		@"reels_swipe_to_profile": @(NO),
		@"stop_story_auto_advance": @(NO),
		@"unlimited_replay": @(NO),
		@"teen_app_icons": @(NO),
		@"SCISelectedAppIconName": @"",
		@"sci_exp_flags_enabled": @(NO),

		@"feed_media_zoom": @(NO),
		@"media_zoom_start_muted": @(NO),
		@"enhanced_media_resolution": @(NO),
		@"disable_bg_refresh": @(NO),
		@"disable_home_refresh": @(NO),
		@"disable_home_scroll": @(NO),
		@"main_feed_mode": @"default",
		@"disable_reels_tab_refresh": @(NO),
		@"dm_full_last_active": @(NO),
		@"bypass_dm_char_limit": @(NO),
		@"send_file": @(NO),
		@"note_actions": @(NO),
		@"note_copy_on_hold": @(NO),
		@"feed_date_format": @"default",
		@"feed_date_custom_templates": @"",
		@"feed_date_show_seconds": @(NO),
		@"feed_date_relative_days_threshold": @(0),
		@"feed_date_compact_relative": @(NO),
		@"feed_date_combine_with_date": @"off",

		@"date_fmt_mixed": @(YES),
		@"date_fmt_notes_comments_stories": @(NO),
		@"date_fmt_dms": @(NO),

		@"feed_action_button": @(YES),
		@"feed_action_default": @"menu",
		@"menu_date_feed": @(NO),
		@"reels_action_button": @(YES),
		@"reels_action_default": @"menu",
		@"menu_date_reels": @(NO),
		@"stories_action_button": @(YES),
		@"stories_action_default": @"menu",
		@"menu_date_stories": @(NO),
		@"dm_visual_action_button": @(YES),
		@"dm_visual_action_default": @"menu",
		@"action_button_icon": @"ellipsis.circle",
		@"action_button_icon_feed": @"",
		@"action_button_icon_reels": @"",
		@"action_button_icon_stories": @"",
		@"action_button_icon_dm": @"",
		@"action_button_icon_profile": @"",

		@"action_menu_cfg_feed": @{},
		@"action_menu_cfg_reels": @{},
		@"action_menu_cfg_stories": @{},
		@"action_menu_cfg_dm": @{},
		@"action_menu_cfg_profile": @{},
		@"action_menu_cfg_instants": @{},

		@"action_button_profile_enabled": @(NO),
		@"action_button_profile_default_action": @"menu",
		@"action_button_profile_default_copy_info_action": @"copy_username",

		@"chat_bg_enabled": @(NO),
		@"chat_bg_default_asset": @"",
		@"chat_bg_thread_map": @{},
		@"chat_bg_thread_meta": @{},
		@"chat_bg_library": @[],
		@"chat_bg_per_image": @{},

		@"sci_gallery_enabled": @(NO),
		@"gallery_save_mode": @"off",
		@"gallery_sort_mode": @(0),
		@"gallery_view_mode": @(0),
		@"show_favorites_at_top": @(NO),
		@"gallery_group_mode": @"off",
		@"dm_tab_long_press_gallery": @(NO),

		@"home_shortcut_enabled": @(NO),
		@"home_shortcut_icon": @"auto",
		@"home_shortcut_actions": @[],
		@"dm_visual_seen_button": @(YES),
		@"dm_visual_audio_toggle": @(NO),

		@"dw_legacy_gesture": @(NO),
		@"dw_confirm": @(NO),
		@"dl_max_concurrent": @(3),
		@"dl_auto_retry": @(YES),
		@"dl_auto_retry_count": @(2),
		@"bg_keepalive": @(YES),
		@"enhance_download_quality": @(YES),
		@"default_video_quality": @"always_ask",
		@"default_photo_quality": @"high",
		@"ffmpeg_encoding_speed": @"ultrafast",
		@"adv_encoding_enabled": @(NO),
		@"adv_video_codec": @"h264_videotoolbox",
		@"adv_preset": @"medium",
		@"adv_tune": @"none",
		@"adv_h264_profile": @"high",
		@"adv_h264_level": @"auto",
		@"adv_crf": @"18",
		@"adv_video_bitrate": @"",
		@"adv_max_resolution": @"original",
		@"adv_fps": @"original",
		@"adv_audio_codec": @"copy",
		@"adv_audio_bitrate": @"128k",
		@"adv_audio_channels": @"original",
		@"adv_audio_samplerate": @"original",
		@"adv_pixel_format": @"yuv420p",
		@"adv_faststart": @(YES),
		@"adv_strip_metadata": @(NO),
		@"unfollow_confirm": @(NO),
		@"sticker_interact_stories_mode": @"off",
		@"sticker_interact_highlights_mode": @"off",
		@"dw_save_action": @"share",
		@"dw_finger_count": @(3),
		@"dw_finger_duration": @(0.5),

		@"reels_tap_control": @"default",
		@"reels_photo_tap_mute": @(NO),
		@"nav_tab_order": @"",
		@"hide_profile_tab": @(NO),
		@"swipe_nav_tabs": @"default",
		@"enable_notes_customization": @(YES),
		@"custom_note_themes": @(YES),
		@"disable_auto_unmuting_reels": @(NO),
		@"settings_shortcut": @(YES),
		@"prevent_doom_scrolling": @(NO),
		@"doom_scrolling_reel_count": @(1),

		@"keep_seen_visual_local": @(NO),
		@"send_audio_as_file": @(YES),
		@"download_audio_message": @(NO),
		@"audio_page_download": @(NO),
		@"save_to_ryukgram_album": @(NO),
		@"gallery_album_name": @"RyukGram",
		@"unlock_password_reels": @(YES),

		@"seen_mode": @"button",
		@"seen_auto_on_interact": @(NO),
		@"seen_auto_on_typing": @(NO),
		@"show_dm_seen_button": @(YES),
		@"show_story_seen_button": @(YES),
		@"confirm_mark_seen_dm": @(NO),
		@"confirm_mark_seen_story": @(NO),
		@"confirm_mark_seen_dm_visual": @(NO),
		@"seen_on_story_like": @(NO),
		@"seen_on_story_reply": @(NO),
		@"advance_on_story_reply": @(NO),
		@"advance_on_mark_seen": @(NO),
		@"advance_on_story_like": @(NO),
		@"dm_visual_advance_on_mark_seen": @(NO),

		@"indicate_unsent_messages": @(NO),
		@"unsent_message_toast": @(NO),
		@"warn_refresh_clears_preserved": @(NO),

		@"read_receipts_enabled": @(NO),
		@"read_receipts_save_log": @(YES),
		@"read_receipts_log_groups": @(NO),

		@"enable_chat_exclusions": @(YES),
		@"chat_blocking_mode": @"block_all",
		@"exclusions_default_keep_deleted": @(NO),
		@"chat_quick_list_button": @(YES),

		@"enable_story_user_exclusions": @(YES),
		@"story_blocking_mode": @"block_all",
		@"story_seen_mode": @"button",
		@"story_audio_toggle": @(NO),
		@"view_story_mentions": @(YES),
		@"story_mentions_button": @(NO),
		@"story_mentions_counter": @(NO),

		@"stories_show_quiz_answer": @(NO),
		@"stories_show_poll_votes_count": @(NO),
		@"reels_show_quiz_answer": @(NO),
		@"reels_show_poll_votes_count": @(NO),
		@"force_enable_quiz_sticker": @(NO),
		@"bypass_reveal_sticker": @(NO),
		@"photo_sticker_allow_video": @(NO),

		@"sci_disable_all": @(NO),

		@"sci_fix_duplicate_notifications": @(YES),

		@"settings_pause_playback": @(YES),
		@"whatsnew_always_show": @(NO),
		@"embed_links": @(NO),
		@"embed_link_domain": @"kkinstagram.com",
		@"strip_tracking_params": @(NO),
		@"download_highlight_cover": @(YES),
		@"open_links_external": @(NO),
		@"strip_browser_tracking": @(NO),

		@"hide_feed_repost": @(NO),
		@"copy_comment": @(YES),
		@"download_gif_comment": @(YES),
		@"custom_gif_comment": @(NO),
		@"gif_favorites_enabled": @(NO),
		@"gif_favorites_list": @[],
		@"skip_sensitive_content": @(NO),

		@"cache_auto_clear_mode": @"off",
		@"cache_auto_check_size": @(YES),
		@"cache_preserve_messages_db": @(YES),
		@"sci_changelog_force_show": @(NO),

		@"live_anonymous_view": @(NO),
		@"live_hide_comments": @(NO),
		@"hide_ui_on_capture": @(NO),
		@"paste_link_from_search": @(NO),
		@"sci_language": @"system",

		@"theme_mode": @"off",
		@"theme_force": @(NO),
		@"theme_oled_chat": @(NO),
		@"theme_keyboard": @"off",

		@"igt_homecoming": @(NO),
		@"igt_quicksnap": @(NO),
		@"igt_prism": @(NO),
		@"igt_directnotes_friendmap": @(NO),
		@"igt_directnotes_audio_reply": @(NO),
		@"igt_directnotes_avatar_reply": @(NO),
		@"igt_directnotes_gifs_reply": @(NO),
		@"igt_directnotes_photo_reply": @(NO),
		@"sci_exp_warning_seen": @(NO),
		@"custom_music_sticker_color": @(NO),
		@"instants_send_from_gallery": @(NO),
		@"instants_allow_screenshot": @(NO),
		@"instants_download_btn": @(NO),
		@"instants_auto_save": @"off",
		@"instants_emoji_reaction_confirm": @(NO),
		@"instants_capture_confirm": @(NO),
		@"instants_advance_confirm": @(NO),
		@"instant_auto_advance_reaction": @(NO),

		@"lock_master_enabled": @(NO),
		@"lock_biometric_enabled": @(YES),
		@"lock_passcode_length": @(4),
		@"lock_chats_locked_entries": @[],
		@"lock_chats_appearance_default": @"icon",
		@"lock_chats_appearance_overrides": @{},
		@"lock_chats_hide_from_inbox": @(NO),
		@"lock_chats_hide_preview": @(NO),
		@"hidden_chats": @[],

		@"lock_app_enabled": @(NO),
		@"lock_app_relock_background": @(YES),
		@"lock_app_idle_timeout": @(0),
		@"lock_app_independent_session": @(YES),
		@"lock_app_relock_on_dismiss": @(NO),

		@"lock_settings_enabled": @(NO),
		@"lock_settings_relock_background": @(NO),
		@"lock_settings_idle_timeout": @(300),
		@"lock_settings_independent_session": @(NO),
		@"lock_settings_relock_on_dismiss": @(NO),

		@"lock_gallery_enabled": @(NO),
		@"lock_gallery_relock_background": @(NO),
		@"lock_gallery_idle_timeout": @(300),
		@"lock_gallery_independent_session": @(NO),
		@"lock_gallery_relock_on_dismiss": @(NO),

		@"lock_keep_deleted_enabled": @(NO),
		@"lock_keep_deleted_relock_background": @(NO),
		@"lock_keep_deleted_idle_timeout": @(300),
		@"lock_keep_deleted_independent_session": @(NO),
		@"lock_keep_deleted_relock_on_dismiss": @(NO),

		@"lock_profile_analyzer_enabled": @(NO),
		@"lock_profile_analyzer_relock_background": @(NO),
		@"lock_profile_analyzer_idle_timeout": @(300),
		@"lock_profile_analyzer_independent_session": @(NO),
		@"lock_profile_analyzer_relock_on_dismiss": @(NO),

		@"lock_messages_tab_enabled": @(NO),
		@"lock_messages_tab_relock_background": @(YES),
		@"lock_messages_tab_idle_timeout": @(0),
		@"lock_messages_tab_independent_session": @(YES),
		@"lock_messages_tab_relock_on_dismiss": @(YES),

		@"lock_chats_enabled": @(NO),
		@"lock_chats_relock_background": @(YES),
		@"lock_chats_idle_timeout": @(0),
		@"lock_chats_independent_session": @(YES),
		@"lock_chats_relock_on_dismiss": @(YES),

		@"notif_master_enabled": @(YES),
		@"notif_style": @"colorful",
		@"notif_position": @"top",
		@"notif_default_surface": @"pill",
		@"notif_max_visible": @(2),
		@"notif_haptics": @(YES),
		@"notif_duration": @(1.0),
		@"notif_mirror_enabled": @(YES),
		@"notif_mirror_clear_on_open": @(YES),
		// ── Dev menu (gates / internal / IGDS / wordmark) ─────────────────
		@"sci_symbol_overrides": @{},
		@"sci_c_symbol_overrides": @{},
		@"sci_c_symbol_id_overrides": @{},
		@"sci_c_symbol_force_enabled": @(NO),
		@"sci_c_symbol_diag_all": @(NO),
		@"sci_apply_bloks_prefetch": @(NO),
		@"sci_apply_force_bloks": @(NO),
		@"sci_apply_internal_native": @(NO),
		@"sci_apply_liquidglass": @(NO),
		@"sci_force_all_mc_gates": @(NO),
		@"sci_force_aura_igplus": @(NO),
		@"sci_force_easy_gating_all": @(NO),
		@"sci_force_easy_gating_auth": @(NO),
		@"sci_force_easy_gating_internal": @(NO),
		@"sci_force_easy_gating_mcq": @(NO),
		@"sci_force_easy_gating_platform": @(NO),
		@"sci_force_employee_defaults_persist": @(NO),
		@"sci_force_ig_creation_internal_label": @(NO),
		@"sci_force_ig_featured_internal_badge": @(NO),
		@"sci_force_ig_inbox_internal_badge": @(NO),
		@"sci_force_ig_internal_apps_installed_after_ios18": @(NO),
		@"sci_force_ig_internal_employee": @(NO),
		@"sci_force_ig_is_employee": @(NO),
		@"sci_force_ig_launch_debug_info": @(NO),
		@"sci_force_ig_launch_debug_info_v2": @(NO),
		@"sci_force_ig_story_debug_underlay": @(NO),
		@"sci_force_igplus_all": @(NO),
		@"sci_igplus_eligibility": @(NO),
		@"sci_igplus_has_access": @(NO),
		@"sci_igplus_any_active": @(NO),
		@"sci_igplus_custom_lists": @(NO),
		@"sci_igplus_story_superlikes": @(NO),
		@"sci_igplus_search_story_viewers": @(NO),
		@"sci_igplus_story_extend": @(NO),
		@"sci_igplus_story_rewatch": @(NO),
		@"sci_igplus_story_peeks": @(NO),
		@"sci_igplus_story_spotlight": @(NO),
		@"sci_igplus_silent_post_highlights": @(NO),
		@"sci_igplus_dm_peek": @(NO),
		@"sci_igplus_custom_app_icon": @(NO),
		@"sci_igplus_branded_threads": @(NO),
		@"sci_igplus_timestamp_viewers": @(NO),
		@"sci_igplus_custom_bio_font": @(NO),
		@"sci_igplus_silent_post_profile": @(NO),
		@"sci_igplus_pinned_posts_limit": @(NO),
		@"sci_igplus_story_peek_active": @(NO),
		@"sci_force_internal_settings_loggedout": @(NO),
		@"sci_force_internal_settings_menu": @(NO),
		@"sci_force_mc_internal_use_all": @(NO),
		@"sci_force_mc_internal_use_boolean": @(NO),
		@"sci_force_mci_experiment_boolean": @(NO),
		@"sci_force_mci_extension_boolean": @(NO),
		@"sci_force_minos_dogfood_mek_encryption": @(NO),
		@"sci_force_mobileconfig_force_update": @(NO),
		@"sci_force_mobileconfig_overrides": @(NO),
		@"sci_force_mobileconfig_try_update": @(NO),
		@"sci_force_msgc_sessioned_boolean": @(NO),
		@"sci_force_sessioned_mc_all": @(NO),
		@"sci_ig_wordmark_mode": @"off",
		@"sci_ig_wordmark_variant": @"off",
		@"sci_igds_animated_waveform": @(NO),
		@"sci_igds_async_font": @(NO),
		@"sci_igds_direct_channels": @(NO),
		@"sci_igds_launcher_all": @(NO),
		@"sci_igds_lg_cgblur": @(NO),
		@"sci_igds_lg_debugger": @(NO),
		@"sci_igds_lg_easeinout": @(NO),
		@"sci_igds_lg_glyphopt": @(NO),
		@"sci_igds_lg_iconbarbtn": @(NO),
		@"sci_igds_lg_inappnotif": @(NO),
		@"sci_igds_lg_navstylepin": @(NO),
		@"sci_igds_lg_toast": @(NO),
		@"sci_igds_lg_toastpeek": @(NO),
		@"sci_igds_liquidglass": @(NO),
		@"sci_igds_nav_bottomsheet": @(NO),
		@"sci_igds_nav_ctxmenu": @(NO),
		@"sci_igds_nav_rounded": @(NO),
		@"sci_igds_nav_tzoom": @(NO),
		@"sci_igds_pagevc_fix": @(NO),
		@"sci_igds_prism": @(NO),
		@"sci_igds_wordmark_isIGWordmark1aAltEnabled": @(NO),
		@"sci_igds_wordmark_isIGWordmark1aEnabled": @(NO),
		@"sci_igds_wordmark_isIGWordmark1bAltEnabled": @(NO),
		@"sci_igds_wordmark_isIGWordmark1bEnabled": @(NO),
		@"sci_internal_gate_crash_disabled_keys": @[],
		@"sci_internal_gate_crash_guard_enabled": @(NO),
		@"sci_internal_gate_crash_last_source": @"",
		@"sci_internal_gate_crash_pending_keys": @[],
		@"sci_internal_menus": @(NO),
		@"sci_statusbar_oldschool": @(NO),
		@"sci_story_tray": @(NO),

		@"sci_mc_adapter_diag": @(NO),
		@"sci_internal_gate_crash_strikes": @(0),
	};
}

void SCIRegisterDefaultsOnce(void) {
	static dispatch_once_t onceToken;
	dispatch_once(&onceToken, ^{
		NSMutableDictionary *defaults = [SCIDefaultsDictionary() mutableCopy];
		[defaults addEntriesFromDictionary:[SCINotificationCenter defaultPerActionPrefs]];
		[defaults addEntriesFromDictionary:[SCINotificationMirror defaultPerActionPrefs]];
		[[NSUserDefaults standardUserDefaults] registerDefaults:defaults];
		[SCIUtils setSciRegisteredDefaults:defaults];
	});
}
